### ISSUE TITLE
Schema registration fails

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Schemas#106]
When using the latest release 0.3.1 of RADAR-Schemas, the registration fails while installing the stack. Here are the logs - 

```
[main] INFO org.radarcns.schema.registration.SchemaRegistry - Registering topic android_phone_user_interaction value schema: org.radarcns.passive.phone.PhoneUserInteraction
[main] INFO org.radarcns.schema.registration.SchemaRegistry - Registering topic android_emotion_faros_acceleration key schema: org.radarcns.kafka.ObservationKey
[main] INFO org.radarcns.schema.registration.SchemaRegistry - Registering topic android_emotion_faros_acceleration value schema: org.radarcns.passive.emotion.EmotionFarosAcceleration
[main] INFO org.radarcns.schema.registration.SchemaRegistry - Registering topic android_emotion_faros_battery_level key schema: org.radarcns.kafka.ObservationKey
[main] INFO org.radarcns.schema.registration.SchemaRegistry - Registering topic android_emotion_faros_battery_level value schema: org.radarcns.passive.empatica.EmpaticaE4BatteryLevel
[main] INFO org.radarcns.schema.registration.SchemaRegistry - Registering topic android_emotion_faros_ecg key schema: org.radarcns.kafka.ObservationKey
[main] INFO org.radarcns.schema.registration.SchemaRegistry - Registering topic android_emotion_faros_ecg value schema: org.radarcns.passive.emotion.EmotionFarosEcg
[main] INFO org.radarcns.schema.registration.SchemaRegistry - Registering topic android_emotion_faros_inter_beat_interval key schema: org.radarcns.kafka.ObservationKey
[main] INFO org.radarcns.schema.registration.SchemaRegistry - Registering topic android_emotion_faros_inter_beat_interval value schema: org.radarcns.passive.emotion.EmotionFarosInterBeatInterval
[main] INFO org.radarcns.schema.registration.SchemaRegistry - Registering topic android_emotion_faros_acceleration key schema: org.radarcns.kafka.ObservationKey
[main] INFO org.radarcns.schema.registration.SchemaRegistry - Registering topic android_emotion_faros_acceleration value schema: org.radarcns.passive.emotion.EmotionFarosTemperature
[main] ERROR org.radarcns.schema.registration.SchemaRegistry - Failed to register schemas for topic android_emotion_faros_acceleration
org.radarcns.producer.rest.RestException: REST call failed (HTTP code 409): {"error_code":409,"message":"Schema being registered is incompatible with an earlier schema"}
	at org.radarcns.producer.rest.RestClient.requestString(RestClient.java:218)
	at org.radarcns.producer.rest.SchemaRetriever.addSchemaMetadata(SchemaRetriever.java:146)
	at org.radarcns.schema.registration.SchemaRegistry.registerSchema(SchemaRegistry.java:103)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at org.radarcns.schema.registration.SchemaRegistry.registerSchemas(SchemaRegistry.java:87)
	at org.radarcns.schema.registration.SchemaRegistry$RegisterCommand.execute(SchemaRegistry.java:188)
	at org.radarcns.schema.CommandLineApp.main(CommandLineApp.java:201)
FAILED TO REGISTER SCHEMAS
### FAILURE ###
```

**Comment by blootsvoets** [comment]
The command will succeed if you specify the `--force` option.
